In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Colab/DM & ML/emails.csv')
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [4]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

In [5]:
df.shape

(5728, 2)

In [6]:
df.columns

Index(['text', 'spam'], dtype='object')

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

#Separate X & Y for dependent & Independent value

In [10]:
x = df.text.values

In [11]:
y = df.spam.values #Dependent

# Split dataset

In [12]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y, test_size=0.2)

# Data preprocessing

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [16]:
cv = CountVectorizer()
x_train = cv.fit_transform(xtrain)
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [2, 0, 0, ..., 0, 0, 0]])

# Naive Bayes Algorithm

In [17]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train,ytrain)

x_test = cv.transform(xtest)

In [18]:
x_test.toarray()

array([[1, 2, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
model.score(x_test,ytest)

0.9929762949956101

In [20]:
emails = ['hey i am looking for a car driver','I will pay him after work as free giveaway as servey']

In [21]:
cv_emails = cv.transform(emails)

In [22]:
model.predict(cv_emails)

array([0, 0])

In [23]:
pred = model.predict(x_test)

pred

array([1, 1, 0, ..., 1, 0, 0])

In [24]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,pred)

0.9929762949956101